server:
  port: 8009
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yzd?characterEncoding=utf8
    username: root
    password: yzd2387143195
  jpa:
    database: MYSQL
    show-sql: true

    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect